# Keep this version in lockstep with apache-airflow in requirements.txt.
FROM apache/airflow:2.10.5-python3.11

USER root
USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
